services:
  ragoo:
    image: ragoo:last
    build: .
    ports:
      - "8001:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - CHROMA_PERSIST_DIR=/app/chroma_data
    volumes:
      - ./app/chroma_data:/app/chroma_data
