name: ragoo CI/CD PIPELINE

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          python -m pip install --upgrade pip        
          pip install -r requirements.txt
          touch .env

      - name: Start FastAPI app
        run: |
          uvicorn ragoo.main:app --host 0.0.0.0 --port 8000 > server.log 2>&1 &
          echo $! > uvicorn.pid
          # Wait for server with retries
          for i in {1..5}; do
            if curl -s -o /dev/null http://127.0.0.1:8000/health; then
              echo "Server started successfully"
              break
            fi
            echo "Waiting for server to start (attempt $i/5)..."
            sleep 5
          done
          # Final startup check
          if ! curl -s -o /dev/null http://127.0.0.1:8000/health; then
            echo "::error::Server failed to start. Logs:"
            cat server.log
            exit 1
          fi

      - name: Check FastAPI /health endpoint
        run: |
          response=$(curl -s http://127.0.0.1:8000/health)
          echo "Raw response: $response"

          # Parse JSON using jq
          status=$(echo "$response" | jq -r '.status')
          service=$(echo "$response" | jq -r '.service')

          if [ "$status" == "OK" ] && [ "$service" == "RAG API" ]; then
            echo "Health check passed"
          else
            echo "::error::Health check failed"
            echo "Expected: status=OK, service='RAG API'"
            echo "Received: status=$status, service='$service'"
            exit 1
          fi
